### ISSUE TITLE
Editing in Chrome Dev tools doesn't sync / update in ST3

### ISSUE THREAD

**Issue by rockethouse** [livestyle/chrome#20]
I've noticed that when I load a website and click the LS icon I can see all the style sheets available and select the one I want to sync, but once I open Chrome Dev tools it stops syncing, and if I click on LS with Dev tools open there are no stylesheets in the list! they disappear!?!

Any ideas what I'm doing wrong? I like to live edit in dev tools and update my css in sublime! thats how it used to work before switching to the Alpha release. 

Thanks

**Comment by sergeche** [comment]
Can you open background page of LiveStyle extension (from extension list preferences page) and post console log here? 

Or maybe some devtools extension breaks?

**Comment by rockethouse** [comment]
Hi,

Here it is: http://cl.ly/2E2D0z3N0l1a

Cheers





On Mon, Jul 13, 2015 at 6:06 PM, Sergey Chikuyonok <notifications@github.com

**Comment by sergeche** [comment]
Thanks. I see that DevTools always returns empty list of stylesheets. I’ll try to figure out what happening there.

Can you try to disable all extensions except LiveStyle and check if it works properly?

**Comment by sergeche** [comment]
Looks like I’ve found issue. Pushed update to Chrome Webstore, make sure LiveStyle Alpha extension is updated to v0.9.2

**Comment by rockethouse** [comment]
Thanks! works perfectly





On Tue, Jul 14, 2015 at 5:48 PM, Sergey Chikuyonok <notifications@github.com
