### ISSUE TITLE
doesn't work, Always prompt “Install Chrome extension”...

### ISSUE THREAD

**Issue by xianghongai** [livestyle/chrome#26]
both browser and editor plugins are installed , LiveStyle app prompt “Install Chrome extension”, Unloading heavy equipment is still the same.

windows7 64-bit, sublime text 3103, sublimeServer, chome 49 .

![livestyle](https://cloud.githubusercontent.com/assets/2075006/14781413/ecee5dd8-0b14-11e6-86c1-7099b75c0a2c.png)

**Comment by sergeche** [comment]
Can you post a full path to your user’s home dir (e.g. `C:\Users\<User dir>)? There might be something with path detection. Anyway, this issue won’t affect your LiveStyle experience

**Comment by xianghongai** [comment]
Sir, I understand, works great, thank you!
